export default [
  {
    firstName: 'Admin',
    lastName: 'Admin',
    middleName: 'Admin',
    status: 'active',
    username: 'admin',
    email: 'admin@email.com',
    userType: 'admin',
    country: 'CD',
    city: 'Kinshasa',
    verified: true,
  },
  {
    firstName: 'lungu',
    lastName: 'lungu',
    middleName: 'lungu',
    status: 'active',
    username: 'lungu',
    email: 'lungu@email.com',
    userType: 'person',
    country: 'CD',
    city: 'Kinshasa',
    verified: true,
  },
  {
    firstName: 'User',
    lastName: 'User',
    middleName: 'User',
    status: 'active',
    username: 'user',
    email: 'user@email.com',
    userType: 'user',
    country: 'CD',
    city: 'Kinshasa',
    verified: true,
  },
];
